/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package portafolio.misofertasescritorio.Offers;


import Models.ProductoElement;
import Services.ServiceOferta;
import Services.ServiceProducto;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;
import portafolio.misofertasescritorio.IconCellRenderer;

/**
 *
 * @author Acer
 */
public final class ListProducts extends javax.swing.JFrame {
    
    //variableLocal
    public static ProductoElement varSessionProductoSelect;
    ServiceProducto serviceProducto = new ServiceProducto();
    
    /**
     * Creates new form MaintainerBusiness
     */
    public ListProducts() {
        initComponents();
        CargarLista();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jYearChooser1 = new com.toedter.calendar.JYearChooser();
        jLocaleChooser1 = new com.toedter.components.JLocaleChooser();
        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProductos = new javax.swing.JTable();
        txtProducto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Empresas");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setBackground(new java.awt.Color(0, 153, 204));
        lblTitulo.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(51, 51, 51));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Lista de Productos");
        jPanel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 260, 50));

        jTableProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Seleccionar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableProductos.setRowHeight(35);
        jTableProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableProductos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 280, 360));

        txtProducto.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        txtProducto.setForeground(new java.awt.Color(102, 102, 102));
        txtProducto.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 127, 0), 2, true), "Buscar Producto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Leelawadee UI Semilight", 1, 14), new java.awt.Color(255, 127, 0))); // NOI18N
        jPanel1.add(txtProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 270, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProductosMouseClicked
        int fila = jTableProductos.rowAtPoint(evt.getPoint());
        int columna = jTableProductos.columnAtPoint(evt.getPoint());
        
        if (columna == 1){
            ProductoElement prod = (ProductoElement) jTableProductos.getValueAt(fila, 0);
            System.out.println(prod);
            varSessionProductoSelect = prod;
            RegisterOffers.txtProducto.setText(prod.toString());
            dispose();
        }
        
    }//GEN-LAST:event_jTableProductosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ListProducts().setVisible(true);
        });
    }
    
    public void CargarLista(){
        
        //recuperar lista producto
        ArrayList<ProductoElement> listaProducto;
        listaProducto = serviceProducto.ListarProductos();
        
        //modelo de la tabla
        DefaultTableModel modelo = (DefaultTableModel) jTableProductos.getModel();
        Object[] O = new Object[2];
        
        //Renderizador de Iconos
        jTableProductos.setDefaultRenderer(Object.class, new IconCellRenderer());
        ImageIcon icon1 = new ImageIcon(getClass().getResource("/images/iconCorrect.png"));
        
        for (int i = 0; i < listaProducto.size(); i++) {
            //Icono seleccionar
            JLabel seleccionar = new JLabel();
            seleccionar.setIcon(icon1);
                
            O[0] =  listaProducto.get(i);
            O[1] =  seleccionar;
            
            modelo.addRow(O);
            
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.components.JLocaleChooser jLocaleChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProductos;
    private com.toedter.calendar.JYearChooser jYearChooser1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtProducto;
    // End of variables declaration//GEN-END:variables
}
