/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package portafolio.misofertasescritorio.Offers;

import Models.Oferta;
import Models.Producto;
import Models.ProductoElement;
import Services.ServiceOferta;
import Services.ServiceProducto;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;
import portafolio.misofertasescritorio.IconCellRenderer;

/**
 *
 * @author Acer
 */
public final class MaintainerOffers extends javax.swing.JFrame {
    
    //variableLocal
    public static int varSessionOferta;
    public static ProductoElement varSessionProducto;
    
    ServiceOferta service = new ServiceOferta();
    ServiceProducto serviceProducto = new ServiceProducto();
    
    /**
     * Creates new form MaintainerBusiness
     */
    public MaintainerOffers() {
        initComponents();
        CargarLista();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jYearChooser1 = new com.toedter.calendar.JYearChooser();
        jLocaleChooser1 = new com.toedter.components.JLocaleChooser();
        jPanel1 = new javax.swing.JPanel();
        btnActualizar = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableOfertas = new javax.swing.JTable();
        btnRegistrar = new javax.swing.JButton();
        lblIcono = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Empresas");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnActualizar.setBackground(new java.awt.Color(255, 255, 255));
        btnActualizar.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 127, 0));
        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconoActualizarLista.png"))); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 127, 0), 2, true));
        jPanel1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 120, 90, 20));

        lblTitulo.setBackground(new java.awt.Color(0, 153, 204));
        lblTitulo.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(51, 51, 51));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Datos de las Ofertas");
        jPanel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 390, 50));

        jTableOfertas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descripcion", "Compra Minima", "Compra Maxima", "Fecha Caducidad", "Valor", "Porcentaje Descuento", "Producto", "Usuario", "Actualizar", "Eliminar", "id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Long.class, java.lang.Long.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Long.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableOfertas.setRowHeight(35);
        jTableOfertas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableOfertasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableOfertas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 810, 280));

        btnRegistrar.setBackground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 127, 0));
        btnRegistrar.setText("Registrar");
        btnRegistrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 127, 0), 2));
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRegistrar.setOpaque(false);
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 170, 40));

        lblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IconoRegistrarUsuario.png"))); // NOI18N
        jPanel1.add(lblIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 60, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableOfertasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableOfertasMouseClicked
        int fila = jTableOfertas.rowAtPoint(evt.getPoint());
        int columna = jTableOfertas.columnAtPoint(evt.getPoint());
        
        if (columna == 6){
            ProductoElement prod = (ProductoElement)jTableOfertas.getValueAt(fila, 6);
            System.out.println(prod);
            varSessionProducto = prod;
            
            InfoProducto infoProducto = new InfoProducto();
            infoProducto.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            infoProducto.setVisible(true);
        }
        
        if (columna == 8) {
            String idOferta = jTableOfertas.getValueAt(fila,10).toString();
            varSessionOferta = Integer.parseInt(idOferta);
            System.out.println(varSessionOferta);
            
            UpdateOffers updateOffers = new UpdateOffers();
            updateOffers.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            updateOffers.setVisible(true);
        }
        
        if (columna == 9) {
            String idOferta = jTableOfertas.getValueAt(fila,10).toString();
            varSessionOferta = Integer.parseInt(idOferta);
            System.out.println(varSessionOferta);
            
            PopupDeleteOffers popupDeleteOffers = new PopupDeleteOffers();
            popupDeleteOffers.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            popupDeleteOffers.setVisible(true);
        }
    }//GEN-LAST:event_jTableOfertasMouseClicked

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
            RegisterOffers registerOffers = new RegisterOffers();
            registerOffers.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            registerOffers.setVisible(true);
    }//GEN-LAST:event_btnRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MaintainerOffers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MaintainerOffers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MaintainerOffers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MaintainerOffers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MaintainerOffers().setVisible(true);
        });
    }
    
    public void CargarLista(){
        //recuperar lista por metodo api
        ArrayList<Oferta> listaOfertas;
        listaOfertas = service.ListarOfertas();
        
        //modelo de la tabla
        DefaultTableModel modelo = (DefaultTableModel) jTableOfertas.getModel();
        Object[] O = new Object[12];
        
        //Renderizador de Iconos
        jTableOfertas.setDefaultRenderer(Object.class, new IconCellRenderer());
        ImageIcon icon1 = new ImageIcon(getClass().getResource("/images/iconoActualizar.png"));
        ImageIcon icon2 = new ImageIcon(getClass().getResource("/images/iconoEliminar.png"));
        
        for (int i = 0; i < listaOfertas.size(); i++) {
            //Icono Actualizar
            JLabel actualizar = new JLabel();
            actualizar.setIcon(icon1);
                
            //Icono Eliminar
            JLabel eliminar = new JLabel();
            eliminar.setIcon(icon2);

            O[0] =  listaOfertas.get(i).getDescripcion();
            O[1] =  listaOfertas.get(i).getCompraMin();
            O[2] =  listaOfertas.get(i).getCompraMax();
            O[3] =  listaOfertas.get(i).getFechaDisponibilidad();
            O[4] =  listaOfertas.get(i).getValor();
            O[5] =  listaOfertas.get(i).getPorcentajeDescuento();
            O[6] =  listaOfertas.get(i).getProducto();
            O[7] =  listaOfertas.get(i).getIDUsuario();
            O[8] =  actualizar;
            O[9] =  eliminar;
            O[10] =  listaOfertas.get(i).getIDOferta();
            
            modelo.addRow(O);
            
        }
        
    }
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnRegistrar;
    private com.toedter.components.JLocaleChooser jLocaleChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableOfertas;
    private com.toedter.calendar.JYearChooser jYearChooser1;
    private javax.swing.JLabel lblIcono;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
