/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package portafolio.misofertasescritorio.Offers;


import Helpers.OfertaHelper;
import Models.Oferta;
import Models.Usuario;
import Services.ServiceOferta;
import Services.ServiceUsuario;
import Services.Validations;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Acer
 */
public final class UpdateOffers extends javax.swing.JFrame {
    
    ServiceOferta serviceOferta = new ServiceOferta();
    ServiceUsuario serviceUsuario = new ServiceUsuario();

    /**
     * Creates new form MaintainerProducts
     */
    public UpdateOffers() {
        initComponents();
        CargarComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDateOferta = new com.toedter.calendar.JDateChooser();
        lblTitulo = new javax.swing.JLabel();
        lblImagenOferta = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtCompraMax = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        txtCompraMin = new javax.swing.JTextField();
        txtPorcDescuento = new javax.swing.JTextField();
        cbcUsuario = new javax.swing.JComboBox<>();
        btnActualizar = new javax.swing.JButton();
        lblIconoGuardar1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar Producto");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 127, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDateOferta.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(jDateOferta, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 290, 40));

        lblTitulo.setBackground(new java.awt.Color(255, 255, 255));
        lblTitulo.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(51, 51, 51));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Ingrese los datos de la Oferta");
        jPanel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 390, 50));

        lblImagenOferta.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        lblImagenOferta.setForeground(new java.awt.Color(120, 120, 120));
        lblImagenOferta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImagenOferta.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 127, 0), 2, true), "Fecha Caducidad", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Leelawadee UI", 1, 14), new java.awt.Color(255, 127, 0))); // NOI18N
        jPanel1.add(lblImagenOferta, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 310, 70));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, 660, 20));

        txtCompraMax.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        txtCompraMax.setForeground(new java.awt.Color(102, 102, 102));
        txtCompraMax.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 127, 0), 2, true), "Compra Maxima", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Leelawadee UI Semilight", 1, 14), new java.awt.Color(255, 127, 0))); // NOI18N
        jPanel1.add(txtCompraMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 140, -1));

        jScrollPane1.setBackground(new java.awt.Color(255, 127, 0));
        jScrollPane1.setBorder(null);
        jScrollPane1.setForeground(new java.awt.Color(255, 127, 0));

        txtDescripcion.setColumns(20);
        txtDescripcion.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        txtDescripcion.setForeground(new java.awt.Color(120, 120, 120));
        txtDescripcion.setLineWrap(true);
        txtDescripcion.setRows(5);
        txtDescripcion.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 127, 0), 2, true), "Descripcion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Leelawadee UI", 1, 14), new java.awt.Color(255, 127, 0))); // NOI18N
        txtDescripcion.setCaretColor(new java.awt.Color(255, 127, 0));
        jScrollPane1.setViewportView(txtDescripcion);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 570, 160));

        jLabel2.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(120, 120, 120));
        jLabel2.setText("Nota*");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, 290, 20));

        jLabel3.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        jLabel3.setText("Precio: Solo debe ser caracteres numericos.");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, 270, 20));

        jLabel4.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        jLabel4.setText("Stock del producto: Solo debe ser caracteres numericos.");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 550, 290, 20));

        jLabel5.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        jLabel5.setText("Descripcion: No debe superar los 500 caracteres.");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 550, 250, 20));

        jLabel6.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        jLabel6.setText("Imagen: tamaño 240 x 240 / Extension JPG o PNG");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 570, 250, 20));

        jLabel7.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        jLabel7.setText("Fecha vencimiento: DD/MM/AAAA");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 570, 270, 20));

        jLabel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 1, true));
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, 600, 100));

        txtPrecio.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        txtPrecio.setForeground(new java.awt.Color(102, 102, 102));
        txtPrecio.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 127, 0), 2, true), "Precio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Leelawadee UI Semilight", 1, 14), new java.awt.Color(255, 127, 0))); // NOI18N
        jPanel1.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 240, -1));

        txtCompraMin.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        txtCompraMin.setForeground(new java.awt.Color(102, 102, 102));
        txtCompraMin.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 127, 0), 2, true), "Compra Minima", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Leelawadee UI Semilight", 1, 14), new java.awt.Color(255, 127, 0))); // NOI18N
        jPanel1.add(txtCompraMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 140, -1));

        txtPorcDescuento.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        txtPorcDescuento.setForeground(new java.awt.Color(102, 102, 102));
        txtPorcDescuento.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 127, 0), 2, true), "Porcentaje Descuento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Leelawadee UI Semilight", 1, 14), new java.awt.Color(255, 127, 0))); // NOI18N
        jPanel1.add(txtPorcDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 240, -1));

        cbcUsuario.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 14)); // NOI18N
        cbcUsuario.setForeground(new java.awt.Color(120, 120, 120));
        cbcUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Leelawadee UI Semilight", 1, 14), new java.awt.Color(255, 127, 0))); // NOI18N
        jPanel1.add(cbcUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 310, 70));

        btnActualizar.setBackground(new java.awt.Color(255, 255, 255));
        btnActualizar.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(78, 204, 44));
        btnActualizar.setText("Actualizar");
        btnActualizar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(78, 204, 44), 2, true));
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 520, 200, 50));

        lblIconoGuardar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconoGuardar.png"))); // NOI18N
        lblIconoGuardar1.setText("jLabel1");
        jPanel1.add(lblIconoGuardar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 520, 60, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 924, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        String compraMin0 = txtCompraMin.getText();
        String compraMax0 = txtCompraMax.getText();
        String descripcion = txtDescripcion.getText();
        DateFormat f = new SimpleDateFormat("yyyy-MM-dd");
        String fechaCaducidad = f.format(jDateOferta.getDate());
        String porcDescuento0 = txtPorcDescuento.getText();
        String precio0 = txtPrecio.getText();
        Usuario usuario = (Usuario)cbcUsuario.getSelectedItem();
        long idUsuario = usuario.getIDUsuario();
        
        //Formateo de entradas
        int compraMin1 = 0;
        int compraMax1 = 0;
        long porcDescuento1;
        long precio1;
        
        //Validaciones
        ArrayList<String> listaErrores = new ArrayList<>();
        
        if (!Validations.validarNoVacio(compraMin0)) {
            listaErrores.add("La compra minima no puede estar en blanco");
        }
        compraMin1 = Validations.validarNumero(compraMin0);
        if (compraMin1 == 0) {
            listaErrores.add("La compra minima no puede contener letras");
        }
        
        if (!Validations.validarNoVacio(compraMax0)) {
            listaErrores.add("La compra maxima no puede estar en blanco");
        }
        compraMax1 = Validations.validarNumero(compraMax0);
        if (compraMax1 == 0) {
            listaErrores.add("La compra maxima no puede contener letras");
        }
        
        if (!Validations.validarNoVacio(descripcion)) {
            listaErrores.add("La descripcion no puede estar en blanco");
        }
        
        if (!Validations.validarNoVacio(porcDescuento0)) {
            listaErrores.add("El porcentaje de descuento no puede estar en blanco");
        }
        porcDescuento1 = Validations.validarNumeroLong(porcDescuento0);
        if (porcDescuento1 == Long.parseLong("0")) {
            listaErrores.add("El porcentaje de descuento no puede contener letras");
        }
        
        if (!Validations.validarNoVacio(precio0)) {
            listaErrores.add("El precio no puede estar en blanco");
        }
        precio1 = Validations.validarNumeroLong(precio0);
        if (precio1 == Long.parseLong("0")) {
            listaErrores.add("El precio no puede contener letras");
        }
        //Fin validaciones
        
        if (listaErrores.isEmpty()) {
            OfertaHelper oferta = new OfertaHelper(descripcion, compraMin1, compraMax1, fechaCaducidad, precio1, porcDescuento1, MaintainerOffers.varSessionUsuario, idUsuario);
            serviceOferta.ActualizarOferta(oferta);
            dispose();
        }else{
            String errores = "";
            for (int i = 0; i < listaErrores.size(); i++) {
                errores += listaErrores.get(i)+"\n";
            }
            JOptionPane.showMessageDialog(null, errores);
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    
    public void CargarComponentes(){
        CargarFiels();
        CargarDatos();
    }
    
    private void CargarDatos() {
        int idOferta = MaintainerOffers.varSessionOferta;
        int idUsuario = MaintainerOffers.varSessionUsuario;
        
        ArrayList<Oferta> listaOfertas;        
        listaOfertas = serviceOferta.ListarOfertas();
        
        for (int i = 0; i < listaOfertas.size(); i++) {
            if (idOferta == listaOfertas.get(i).getIDOferta()) {
                txtCompraMin.setText(Long.toString(listaOfertas.get(i).getCompraMin()));
                txtCompraMax.setText(Long.toString(listaOfertas.get(i).getCompraMax()));
                txtPorcDescuento.setText(Long.toString(listaOfertas.get(i).getPorcentajeDescuento()));
                DateFormat f = new SimpleDateFormat("yyyy-MM-dd");
                Date date = null;
                try{
                    date = f.parse(listaOfertas.get(i).getFechaDisponibilidad());
                }catch (ParseException e) {
                    e.printStackTrace();
                }
                jDateOferta.setDate(date);
                txtPrecio.setText(Long.toString(listaOfertas.get(i).getValor()));
                txtDescripcion.setText(listaOfertas.get(i).getDescripcion());
                cbcUsuario.setSelectedItem(BuscarUsuario(idUsuario));
            }
        }
    }
    
    private Usuario CargarFiels() {
        ArrayList<Usuario> listaUsuario;
        listaUsuario = serviceUsuario.ListarUsuarios();
        Usuario user = null;
        
        for (int i = 0; i < listaUsuario.size(); i++) {
            cbcUsuario.addItem(listaUsuario.get(i));
            if (MaintainerOffers.varSessionUsuario == listaUsuario.get(i).getIDUsuario()) {
                user = listaUsuario.get(i);
            }
        }
        return user;
    }
    
    private Usuario BuscarUsuario(int idUsuario){
        ArrayList<Usuario> listaUsuario;
        listaUsuario = serviceUsuario.ListarUsuarios();
        Usuario user = null;
        
        for (int i = 0; i < listaUsuario.size(); i++) {
            cbcUsuario.addItem(listaUsuario.get(i));
            if (MaintainerOffers.varSessionUsuario == listaUsuario.get(i).getIDUsuario()) {
                user = listaUsuario.get(i);
                break;
            }
        }
        return user;
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateOffers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateOffers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateOffers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateOffers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new UpdateOffers().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JComboBox<Usuario> cbcUsuario;
    private com.toedter.calendar.JDateChooser jDateOferta;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblIconoGuardar1;
    private javax.swing.JLabel lblImagenOferta;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtCompraMax;
    private javax.swing.JTextField txtCompraMin;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtPorcDescuento;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables

}
