/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package portafolio.misofertasescritorio.products;

import Helpers.ProductoHelper;
import Models.Categoria;
import Models.Empresas;
import Models.ProductoElement;
import Services.ServiceEmpresa;
import Services.ServiceProducto;
import Services.Validations;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Acer
 */
public final class UpdateProducts extends javax.swing.JFrame {
    
    ServiceProducto servicio = new ServiceProducto();
    ServiceEmpresa servicioEmpresa = new ServiceEmpresa();

    /**
     * Creates new form MaintainerProducts
     */
    public UpdateProducts() {
        initComponents();
        CargarComponentes();
        CargarProducto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        txtImagen = new javax.swing.JTextField();
        cbcEmpresa = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        txtStockProducto = new javax.swing.JTextField();
        txtNombreProducto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        lblIconoGuardar = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtPrecioProducto = new javax.swing.JTextField();
        cbcCategoriaProducto = new javax.swing.JComboBox<>();
        txtModelo = new javax.swing.JTextField();
        txtTemporada = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        lblImagenOferta1 = new javax.swing.JLabel();
        jDateFechaVencimiento = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar Producto");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 127, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setBackground(new java.awt.Color(255, 255, 255));
        lblTitulo.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(51, 51, 51));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Actualize los datos del Producto");
        jPanel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 390, 50));

        txtImagen.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        txtImagen.setForeground(new java.awt.Color(102, 102, 102));
        txtImagen.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 127, 0), 2, true), "Imagen", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Leelawadee UI Semilight", 1, 14), new java.awt.Color(255, 127, 0))); // NOI18N
        jPanel1.add(txtImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 350, -1));

        cbcEmpresa.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 14)); // NOI18N
        cbcEmpresa.setForeground(new java.awt.Color(120, 120, 120));
        cbcEmpresa.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 127, 0), 0, true), "Empresa Patrocinadora", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Leelawadee UI Semilight", 1, 14), new java.awt.Color(255, 127, 0))); // NOI18N
        jPanel1.add(cbcEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 330, 50));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 600, 580, 10));

        txtStockProducto.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        txtStockProducto.setForeground(new java.awt.Color(102, 102, 102));
        txtStockProducto.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 127, 0), 2, true), "Stock del producto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Leelawadee UI Semilight", 1, 14), new java.awt.Color(255, 127, 0))); // NOI18N
        jPanel1.add(txtStockProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 160, -1));

        txtNombreProducto.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        txtNombreProducto.setForeground(new java.awt.Color(102, 102, 102));
        txtNombreProducto.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 127, 0), 2, true), "Nombre del producto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Leelawadee UI Semilight", 1, 14), new java.awt.Color(255, 127, 0))); // NOI18N
        jPanel1.add(txtNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 730, -1));

        jScrollPane1.setBackground(new java.awt.Color(255, 127, 0));
        jScrollPane1.setBorder(null);
        jScrollPane1.setForeground(new java.awt.Color(255, 127, 0));

        txtDescripcion.setColumns(20);
        txtDescripcion.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        txtDescripcion.setForeground(new java.awt.Color(120, 120, 120));
        txtDescripcion.setLineWrap(true);
        txtDescripcion.setRows(5);
        txtDescripcion.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 127, 0), 2, true), "Descripcion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Leelawadee UI", 1, 14), new java.awt.Color(255, 127, 0))); // NOI18N
        txtDescripcion.setCaretColor(new java.awt.Color(255, 127, 0));
        jScrollPane1.setViewportView(txtDescripcion);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 730, -1));

        lblIconoGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconoGuardar.png"))); // NOI18N
        lblIconoGuardar.setText("jLabel1");
        jPanel1.add(lblIconoGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 640, 60, 50));

        btnActualizar.setBackground(new java.awt.Color(255, 255, 255));
        btnActualizar.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(78, 204, 44));
        btnActualizar.setText("Actualizar");
        btnActualizar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(78, 204, 44), 2, true));
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 640, 200, 50));

        jLabel2.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(120, 120, 120));
        jLabel2.setText("Nota*");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 620, 290, 20));

        jLabel3.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        jLabel3.setText("Precio: Solo debe ser caracteres numericos.");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 650, 270, -1));

        jLabel4.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        jLabel4.setText("Stock del producto: Solo debe ser caracteres numericos.");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 670, 280, -1));

        jLabel5.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        jLabel5.setText("Descripcion: No debe superar los 500 caracteres.");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 650, 250, -1));

        jLabel6.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        jLabel6.setText("Imagen: tamaño 240 x 240 / Extension JPG o PNG");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 670, 250, -1));

        jLabel7.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        jLabel7.setText("Fecha vencimiento: DD/MM/AAAA");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 690, 270, -1));

        jLabel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 1, true));
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 620, 640, 90));

        txtPrecioProducto.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        txtPrecioProducto.setForeground(new java.awt.Color(102, 102, 102));
        txtPrecioProducto.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 127, 0), 2, true), "Precio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Leelawadee UI Semilight", 1, 14), new java.awt.Color(255, 127, 0))); // NOI18N
        jPanel1.add(txtPrecioProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 340, -1));

        cbcCategoriaProducto.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 14)); // NOI18N
        cbcCategoriaProducto.setForeground(new java.awt.Color(102, 102, 102));
        cbcCategoriaProducto.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 127, 0), 0, true), "Categoria", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Leelawadee UI Semilight", 1, 14), new java.awt.Color(255, 127, 0))); // NOI18N
        jPanel1.add(cbcCategoriaProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 340, 50));

        txtModelo.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        txtModelo.setForeground(new java.awt.Color(102, 102, 102));
        txtModelo.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 127, 0), 2, true), "Modelo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Leelawadee UI Semilight", 1, 14), new java.awt.Color(255, 127, 0))); // NOI18N
        jPanel1.add(txtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, 340, -1));

        txtTemporada.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        txtTemporada.setForeground(new java.awt.Color(102, 102, 102));
        txtTemporada.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 127, 0), 2, true), "Temporada", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Leelawadee UI Semilight", 1, 14), new java.awt.Color(255, 127, 0))); // NOI18N
        jPanel1.add(txtTemporada, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, 340, -1));

        txtMarca.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        txtMarca.setForeground(new java.awt.Color(102, 102, 102));
        txtMarca.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 127, 0), 2, true), "Marca", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Leelawadee UI Semilight", 1, 14), new java.awt.Color(255, 127, 0))); // NOI18N
        jPanel1.add(txtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 340, -1));

        lblImagenOferta1.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        lblImagenOferta1.setForeground(new java.awt.Color(120, 120, 120));
        lblImagenOferta1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImagenOferta1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 127, 0), 2, true), "Fecha Caducidad", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Leelawadee UI", 1, 14), new java.awt.Color(255, 127, 0))); // NOI18N
        jPanel1.add(lblImagenOferta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 170, 60));
        jPanel1.add(jDateFechaVencimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 150, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 721, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        
        String nombre = txtNombreProducto.getText();
        String precioNormal0 = txtPrecioProducto.getText();
        String descripcion = txtDescripcion.getText();
        String marca = txtMarca.getText();
        String modelo = txtModelo.getText();
        String stock0 = txtStockProducto.getText();
        String imagen = txtImagen.getText();
        SimpleDateFormat f = new SimpleDateFormat("yyyy/MM/dd");
        String fechaVencimiento = f.format(jDateFechaVencimiento.getDate());
        String temporada = txtTemporada.getText();
        Categoria categoria = (Categoria)cbcCategoriaProducto.getSelectedItem();
        long idCategoria = categoria.getIDCategoria();
        Empresas empresa = (Empresas)cbcEmpresa.getSelectedItem();
        long idEmpresa = empresa.getIDEmpresa();
        
        //Formateo de entradas
        Long precioNormal1 = null;
        Long stock1 = null;
        
        //Fin de formateo de entradas
        
        //Validaciones
        ArrayList<String> listaErrores = new ArrayList<>();
        
        if (!Validations.validarNoVacio(nombre)) {
            listaErrores.add("El nombre del producto no puede estar en blanco");
        }
        
        if (!Validations.validarNoVacio(precioNormal0)) {
            listaErrores.add("El precio del producto no puede estar en blanco");
        }
        precioNormal1 = Validations.validarNumeroLong(precioNormal0);
        if (precioNormal1 == Long.parseLong("0")) {
            listaErrores.add("El precio del producto no puede contener letras");
        }
        
        if (!Validations.validarNoVacio(descripcion)) {
            listaErrores.add("La descripcion del producto no puede estar en blanco");
        }
        
        if (!Validations.validarNoVacio(marca)) {
            listaErrores.add("La marca del producto no puede estar en blanco");
        }
        
        if (!Validations.validarNoVacio(modelo)) {
            listaErrores.add("El modelo del producto no puede estar en blanco");
        }
        
        
        if (!Validations.validarNoVacio(stock0)) {
            listaErrores.add("El stock del producto no puede estar en blanco");
        }
        stock1 = Validations.validarNumeroLong(stock0);
        if (stock1 == Long.parseLong("0")) {
            listaErrores.add("El stock no puede contener letras");
        }
        
        if (!Validations.validarNoVacio(temporada)) {
            listaErrores.add("La temporada del producto no puede estar en blanco");
        }
        //Fin validaciones
        
        //Agregar producto
        if (listaErrores.isEmpty()) {
            ProductoHelper producto = new ProductoHelper(nombre, precioNormal1, descripcion, marca, modelo, stock1, imagen, fechaVencimiento, temporada, idEmpresa, idCategoria);
            servicio.ActualizarProducto(producto);
            dispose();
        }else{
            String errores = "";
            for (int i = 0; i < listaErrores.size(); i++) {
                errores += listaErrores.get(i)+"\n";
            }
            JOptionPane.showMessageDialog(null, errores);
        }
        //Fin de agregar producto
        
        
        
        
    }//GEN-LAST:event_btnActualizarActionPerformed

    
    public void CargarComponentes(){
        //Recuperar lista de categoria
        ArrayList<Categoria> listaCategoria;
        listaCategoria = servicio.ListarCategorias();
        
        for (int i = 0; i < listaCategoria.size(); i++) {
            cbcCategoriaProducto.addItem(listaCategoria.get(i));
        }
        
        //Recuperar lista de empresas
        ArrayList<Empresas> listaEmpresas;
        listaEmpresas = servicioEmpresa.ListarEmpresas();
        
        for (int i = 0; i < listaEmpresas.size(); i++) {
            cbcEmpresa.addItem(listaEmpresas.get(i));
        }
    }
    
    public void CargarProducto(){
        int idProducto = MaintainerProducts.varSessionProducto;
        ArrayList<ProductoElement> listaProductos;
        listaProductos = servicio.ListarProductos();
        
        for (int i = 0; i < listaProductos.size(); i++) {
            if (idProducto == listaProductos.get(i).getIDProducto()) {
                
                txtNombreProducto.setText(listaProductos.get(i).getNombre());
                txtPrecioProducto.setText(Long.toString(listaProductos.get(i).getPrecioNormal()));
                txtDescripcion.setText(listaProductos.get(i).getDescripcion());
                txtMarca.setText(listaProductos.get(i).getMarca());
                txtModelo.setText(listaProductos.get(i).getModelo());
                txtStockProducto.setText(Long.toString(listaProductos.get(i).getStock()));
                txtImagen.setText(listaProductos.get(i).getImagen());
                DateFormat f = new SimpleDateFormat("yyyy-MM-dd");
                Date date = null;
                try{
                    date = f.parse(listaProductos.get(i).getFechaVencimiento());
                }catch (ParseException e) {
                    e.printStackTrace();
                }
                jDateFechaVencimiento.setDate(date);
                txtTemporada.setText(listaProductos.get(i).getTemporada());
                cbcCategoriaProducto.setSelectedItem(recuperarCategoria(listaProductos.get(i).getIDCategoria()));
                cbcEmpresa.setSelectedItem(recuperarEmpresa(listaProductos.get(i).getIDEmpresa()));
                
            }
        }
        
    }
    
    public Categoria recuperarCategoria(long id){
        ArrayList<Categoria> listaCategoria;
        listaCategoria = servicio.ListarCategorias();
        Categoria categoria = null;
        
        for (int i = 0; i < listaCategoria.size(); i++) {
            if (id == listaCategoria.get(i).getIDCategoria()) {
                categoria = listaCategoria.get(i);
            }
        }
        return categoria;
    }
    
    public Empresas recuperarEmpresa(long id){
        ArrayList<Empresas> listaEmpresas;
        listaEmpresas = servicioEmpresa.ListarEmpresas();
        Empresas empresa = null;
        
        for (int i = 0; i < listaEmpresas.size(); i++) {
            if (id == listaEmpresas.get(i).getIDEmpresa()) {
                empresa = listaEmpresas.get(i);
            }
        }
        return empresa;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
             
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateProducts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JComboBox<Categoria> cbcCategoriaProducto;
    private javax.swing.JComboBox<Empresas> cbcEmpresa;
    private com.toedter.calendar.JDateChooser jDateFechaVencimiento;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblIconoGuardar;
    private javax.swing.JLabel lblImagenOferta1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtImagen;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtNombreProducto;
    private javax.swing.JTextField txtPrecioProducto;
    private javax.swing.JTextField txtStockProducto;
    private javax.swing.JTextField txtTemporada;
    // End of variables declaration//GEN-END:variables
}
