/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package portafolio.misofertasescritorio;

import Models.UserSession;
import Models.Usuario;
import Services.ServiceUsuario;
import Services.UserServices;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author cvargas
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonEntrar = new javax.swing.JButton();
        textCorreo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        textPassword = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ingresar al sistema");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonEntrar.setBackground(new java.awt.Color(255, 255, 255));
        buttonEntrar.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        buttonEntrar.setForeground(new java.awt.Color(255, 127, 0));
        buttonEntrar.setText("Ingresar");
        buttonEntrar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 127, 0), 3, true));
        buttonEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEntrarActionPerformed(evt);
            }
        });
        jPanel1.add(buttonEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 130, 40));

        textCorreo.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        textCorreo.setForeground(new java.awt.Color(122, 122, 122));
        textCorreo.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 127, 0), 1, true), "Correo Electronico", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Leelawadee UI Semilight", 1, 11), new java.awt.Color(255, 127, 0))); // NOI18N
        jPanel1.add(textCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 320, 50));

        jLabel1.setFont(new java.awt.Font("Leelawadee UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(120, 120, 120));
        jLabel1.setText("Bienvenido");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, -1, -1));

        textPassword.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        textPassword.setForeground(new java.awt.Color(122, 122, 122));
        textPassword.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 127, 0), 1, true), "Password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Leelawadee UI", 1, 12), new java.awt.Color(255, 127, 0))); // NOI18N
        jPanel1.add(textPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 320, 50));

        jPanel2.setBackground(new java.awt.Color(255, 127, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 220, 190));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconoIngresaSistema.png"))); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 127, 0)));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -20, 240, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEntrarActionPerformed
            
        
        
            ServiceUsuario service = new ServiceUsuario();
            
            ArrayList<Usuario> listaUsuario;
            
            listaUsuario = service.ListarUsuarios();
            
            String respuesta = "";
            String correo = textCorreo.getText();
            String password = textPassword.getText();
            
            Boolean validarCorreo = false;
            Boolean validarPassword = false;
        
        
            for (int i = 0; i < listaUsuario.size(); i++) {
                if (password.equals(listaUsuario.get(i).getPassword()) && correo.equals(listaUsuario.get(i).getCorreo()) ){
                       validarCorreo = true;
                       validarPassword = true;
                }
                
            }
            
            if (validarCorreo==true&&validarPassword==true) {
                AdminStart adminStart = new AdminStart();
                adminStart.setVisible(true);
                dispose();
            }else{
                JOptionPane.showMessageDialog(null, "Error de usuario y password");
            }
            
            
        
/**        
            int usertype = 1;
            UserSession response = UserServices.PostUserLogin(textCorreo.getText(), textPassword.getText(), usertype);
            
            System.out.println(response);
         
            if (response.IsSuccess) {
               
                AdminStart adminStart = new AdminStart();
                adminStart.setVisible(true);
                setVisible(false);
                
            }else{
                JOptionPane.showMessageDialog(null, response.Message);
            }
**/ 
        
    }//GEN-LAST:event_buttonEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEntrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField textCorreo;
    private javax.swing.JTextField textPassword;
    // End of variables declaration//GEN-END:variables
}
